# Generated by Django 4.1 on 2022-09-11 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedia',
            name='link',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
